/*
 * Note: this file originally auto-generated by mib2c using
 *  $
 *
 * $Id:$
 */
#ifndef LINKTABLE_OIDS_H
#define LINKTABLE_OIDS_H

#ifdef __cplusplus
extern          "C" {
#endif


    /*
     * column number definitions for table linkTable 
     */
#define LINKTABLE_OID              1,3,6,1,4,1,36872,2,1,1,1


#define COLUMN_LINKINDEX         1

#define COLUMN_LINKID         2

#define COLUMN_SLC         3

#define COLUMN_CORSET         4

#define COLUMN_TXPORT         5

#define COLUMN_TXCHAN         6

#define COLUMN_TXBRAN         7

#define COLUMN_TXBRMGR         8

#define COLUMN_CORBRMGR         9

#define COLUMN_CORBRCON         10

#define COLUMN_PROTOCOL         11

#define COLUMN_TIME         12

#define COLUMN_TXISUP         13

#define COLUMN_RXISUP         14

#define COLUMN_TXSCCP         15

#define COLUMN_RXSCCP         16

#define COLUMN_TXSNMM         17

#define COLUMN_RXSNMM         18

#define COLUMN_TXFISU         19

#define COLUMN_RXFISU         20

#define COLUMN_TXOTHER         21

#define COLUMN_RXOTHER         22

#define COLUMN_TXERR         23

#define COLUMN_RXERR         24

#define COLUMN_TXERRRATE         25

#define COLUMN_RXERRRATE         26

#define COLUMN_UNITID         27

#define COLUMN_LINKSET         28

#define COLUMN_ORIGINCLLI         29

#define COLUMN_DESTINCLLI         30

#define COLUMN_ORIGINPTCD         31

#define COLUMN_DESTINPTCD         32


#define LINKTABLE_MIN_COL   COLUMN_LINKID
#define LINKTABLE_MAX_COL   COLUMN_DESTINPTCD



#ifdef __cplusplus
}
#endif
#endif                          /* LINKTABLE_OIDS_H */
