/*
 * Note: this file originally auto-generated by mib2c using
 *       version $ of $
 *
 * $Id:$
 *
 * @file linkTable_data_get.h
 *
 * @addtogroup get
 *
 * Prototypes for get functions
 *
 * @{
 */
#ifndef LINKTABLE_DATA_GET_H
#define LINKTABLE_DATA_GET_H

#ifdef __cplusplus
extern          "C" {
#endif

    /*
     *********************************************************************
     * GET function declarations
     */

    /*
     *********************************************************************
     * GET Table declarations
     */
/**********************************************************************
 **********************************************************************
 ***
 *** Table linkTable
 ***
 **********************************************************************
 **********************************************************************/
    /*
     * MYCORP-PRODUCT-MYPRODUCT-MIB::linkTable is subid 1 of myCorpProductMIB.
     * Its status is Current.
     * OID: .1.3.6.1.4.1.36872.2.1.1.1, length: 11
     */
    /*
     * indexes
     */

    int             linkID_get(linkTable_rowreq_ctx * rowreq_ctx,
                               u_long * linkID_val_ptr);
    int             slc_get(linkTable_rowreq_ctx * rowreq_ctx,
                            u_long * slc_val_ptr);
    int             corSet_get(linkTable_rowreq_ctx * rowreq_ctx,
                               u_long * corSet_val_ptr);
    int             txPort_get(linkTable_rowreq_ctx * rowreq_ctx,
                               u_long * txPort_val_ptr);
    int             txChan_get(linkTable_rowreq_ctx * rowreq_ctx,
                               u_long * txChan_val_ptr);
    int             txBran_get(linkTable_rowreq_ctx * rowreq_ctx,
                               u_long * txBran_val_ptr);
    int             txBrMgr_get(linkTable_rowreq_ctx * rowreq_ctx,
                                u_long * txBrMgr_val_ptr);
    int             corBrMgr_get(linkTable_rowreq_ctx * rowreq_ctx,
                                 u_long * corBrMgr_val_ptr);
    int             corBrCon_get(linkTable_rowreq_ctx * rowreq_ctx,
                                 u_long * corBrCon_val_ptr);
    int             protocol_get(linkTable_rowreq_ctx * rowreq_ctx,
                                 char **protocol_val_ptr_ptr,
                                 size_t *protocol_val_ptr_len_ptr);
    int             time_get(linkTable_rowreq_ctx * rowreq_ctx,
                             u_long * time_val_ptr);
    int             txISUP_get(linkTable_rowreq_ctx * rowreq_ctx,
                               u_long * txISUP_val_ptr);
    int             rxISUP_get(linkTable_rowreq_ctx * rowreq_ctx,
                               u_long * rxISUP_val_ptr);
    int             txSCCP_get(linkTable_rowreq_ctx * rowreq_ctx,
                               u_long * txSCCP_val_ptr);
    int             rxSCCP_get(linkTable_rowreq_ctx * rowreq_ctx,
                               u_long * rxSCCP_val_ptr);
    int             txSNMM_get(linkTable_rowreq_ctx * rowreq_ctx,
                               u_long * txSNMM_val_ptr);
    int             rxSNMM_get(linkTable_rowreq_ctx * rowreq_ctx,
                               u_long * rxSNMM_val_ptr);
    int             txFISU_get(linkTable_rowreq_ctx * rowreq_ctx,
                               u_long * txFISU_val_ptr);
    int             rxFISU_get(linkTable_rowreq_ctx * rowreq_ctx,
                               u_long * rxFISU_val_ptr);
    int             txOther_get(linkTable_rowreq_ctx * rowreq_ctx,
                                u_long * txOther_val_ptr);
    int             rxOther_get(linkTable_rowreq_ctx * rowreq_ctx,
                                u_long * rxOther_val_ptr);
    int             txErr_get(linkTable_rowreq_ctx * rowreq_ctx,
                              u_long * txErr_val_ptr);
    int             rxErr_get(linkTable_rowreq_ctx * rowreq_ctx,
                              u_long * rxErr_val_ptr);
    int             txErrRate_get(linkTable_rowreq_ctx * rowreq_ctx,
                                  u_long * txErrRate_val_ptr);
    int             rxErrRate_get(linkTable_rowreq_ctx * rowreq_ctx,
                                  u_long * rxErrRate_val_ptr);
    int             unitID_get(linkTable_rowreq_ctx * rowreq_ctx,
                               u_long * unitID_val_ptr);
    int             linkSet_get(linkTable_rowreq_ctx * rowreq_ctx,
                                u_long * linkSet_val_ptr);
    int             originCLLI_get(linkTable_rowreq_ctx * rowreq_ctx,
                                   char **originCLLI_val_ptr_ptr,
                                   size_t *originCLLI_val_ptr_len_ptr);
    int             destinCLLI_get(linkTable_rowreq_ctx * rowreq_ctx,
                                   char **destinCLLI_val_ptr_ptr,
                                   size_t *destinCLLI_val_ptr_len_ptr);
    int             originPtCd_get(linkTable_rowreq_ctx * rowreq_ctx,
                                   u_long * originPtCd_val_ptr);
    int             destinPtCd_get(linkTable_rowreq_ctx * rowreq_ctx,
                                   u_long * destinPtCd_val_ptr);


    int             linkTable_indexes_set_tbl_idx(linkTable_mib_index *
                                                  tbl_idx,
                                                  u_long linkIndex_val);
    int             linkTable_indexes_set(linkTable_rowreq_ctx *
                                          rowreq_ctx,
                                          u_long linkIndex_val);




#ifdef __cplusplus
}
#endif
#endif                          /* LINKTABLE_DATA_GET_H */
/** @} */
