/*
 * Note: this file originally auto-generated by mib2c using
 *       version $ of $
 *
 * $Id:$
 */
/** @ingroup interface: Routines to interface to Net-SNMP
 *
 * \warning This code should not be modified, called directly,
 *          or used to interpret functionality. It is subject to
 *          change at any time.
 * 
 * @{
 */
/*
 * *********************************************************************
 * *********************************************************************
 * *********************************************************************
 * ***                                                               ***
 * ***  NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE  ***
 * ***                                                               ***
 * ***                                                               ***
 * ***       THIS FILE DOES NOT CONTAIN ANY USER EDITABLE CODE.      ***
 * ***                                                               ***
 * ***                                                               ***
 * ***       THE GENERATED CODE IS INTERNAL IMPLEMENTATION, AND      ***
 * ***                                                               ***
 * ***                                                               ***
 * ***    IS SUBJECT TO CHANGE WITHOUT WARNING IN FUTURE RELEASES.   ***
 * ***                                                               ***
 * ***                                                               ***
 * *********************************************************************
 * *********************************************************************
 * *********************************************************************
 */
#ifndef LINKTABLE_INTERFACE_H
#define LINKTABLE_INTERFACE_H

#ifdef __cplusplus
extern          "C" {
#endif


#include "linkTable.h"


    /*
     ********************************************************************
     * Table declarations
     */

    /*
     * PUBLIC interface initialization routine 
     */
    void            _linkTable_initialize_interface(linkTable_registration
                                                    * user_ctx,
                                                    u_long flags);
    void            _linkTable_shutdown_interface(linkTable_registration *
                                                  user_ctx);

    linkTable_registration *linkTable_registration_get(void);

    linkTable_registration
        *linkTable_registration_set(linkTable_registration * newreg);

    netsnmp_container *linkTable_container_get(void);
    int             linkTable_container_size(void);

    linkTable_rowreq_ctx *linkTable_allocate_rowreq_ctx(void);
    void            linkTable_release_rowreq_ctx(linkTable_rowreq_ctx *
                                                 rowreq_ctx);

    int             linkTable_index_to_oid(netsnmp_index * oid_idx,
                                           linkTable_mib_index * mib_idx);
    int             linkTable_index_from_oid(netsnmp_index * oid_idx,
                                             linkTable_mib_index *
                                             mib_idx);

    /*
     * access to certain internals. use with caution!
     */
    void            linkTable_valid_columns_set(netsnmp_column_info *vc);


#ifdef __cplusplus
}
#endif
#endif                          /* LINKTABLE_INTERFACE_H */
/** @} */
