/*
 * Note: this file originally auto-generated by mib2c using
 *       version $ of $ 
 *
 * $Id:$
 */
#ifndef LINKTABLE_DATA_SET_H
#define LINKTABLE_DATA_SET_H

#ifdef __cplusplus
extern          "C" {
#endif

    /*
     *********************************************************************
     * SET function declarations
     */

    /*
     *********************************************************************
     * SET Table declarations
     */


#ifdef __cplusplus
}
#endif
#endif                          /* LINKTABLE_DATA_SET_H */
